packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  lightningcss: true
  unrs-resolver: true
  msw: false

catalog:
  drizzle-orm: 1.0.0-rc.4
  drizzle-kit: 1.0.0-rc.4
  "@tanstack/react-router": latest
  sonner: "^2.0.7"